# Site settings
title: Juliet's playground
email: juliet.zhu.work@gmail.com
description: "Julet's playground"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  juliet-zhu

# Build settings
markdown: kramdown
permalink: pretty
